# AUTOGENERATED! DO NOT EDIT! File to edit: ../00_core.ipynb.

# %% auto 0
__all__ = ['HelloElement', 'mass_error_ppm']

# %% ../00_core.ipynb 4
from molmass.elements import ELEMENTS

# %% ../00_core.ipynb 5
class HelloElement:
    "Meet the `element`!"
   
    def __init__(self, element: str): self.element = ELEMENTS[element]
        
    def fun_fact(self):
        "Fun fact about me."
        return self.element.description

# %% ../00_core.ipynb 9
def mass_error_ppm(theor: float, obsvd: float):
    """Calculate relative mass error."""
    return round(1e6*(obsvd/theor - 1), 2)
