project:
  type: website
  output-dir: _docs
  preview:
    port: 3000
    browser: false

format:
  html:
    page-layout: article
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    toc-depth: 4

website:
  title: "nbdev-demo"
  site-url: "https://enveda.github.io/nbdev-demo"
  description: "nbdev-demonstration"
  twitter-card: true
  open-graph: true
  repo-branch: master
  repo-url: "https://github.com/enveda/nbdev-demo"
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
    right:
      - icon: github
        href: "https://github.com/enveda/nbdev-demo"
  sidebar:
    style: "docked"

metadata-files: 
  - sidebar.yml
  - custom.yml
